### ISSUE TITLE
Use this in a tkinter gui

### ISSUE THREAD

**Issue by pythonnewbie3** [lithium0003/JSME_ipywidget#1]
Hi,

I wrote a computer application with a tkinter gui. Can I intergrate this into my program so the user can draw his molecule and this will
return the smiles? Can I send smiles to this editor and change the groups in the editor and return the new molecule as smiles?

Thank you in advance.

**Comment by lithium0003** [comment]
[JSME Molecule Editor](https://jsme-editor.github.io/) is a javascript base molecule editor. So you need some web browser component to use this editor. This repository is a ipywidget implementation for JSME molecule Editor, which is using it as is, is wrapped with ipywidget so that can use in jupyter notebook.

**Comment by pythonnewbie3** [comment]
Ok, thank you for your reply. I guess I need to use a different editor than. Thanks.
